//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoCliClient.ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TodoItem", Namespace="http://schemas.datacontract.org/2004/07/TodoWCFService.Models")]
    public partial class TodoItem : object
    {
        
        private bool DoneField;
        
        private string IDField;
        
        private string NameField;
        
        private string NotesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Done
        {
            get
            {
                return this.DoneField;
            }
            set
            {
                this.DoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TodoCliClient.ServiceReference.ITodoService")]
    public interface ITodoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/GetTodoItems", ReplyAction="http://tempuri.org/ITodoService/GetTodoItemsResponse")]
        System.Threading.Tasks.Task<TodoCliClient.ServiceReference.TodoItem[]> GetTodoItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/CreateTodoItem", ReplyAction="http://tempuri.org/ITodoService/CreateTodoItemResponse")]
        System.Threading.Tasks.Task CreateTodoItemAsync(TodoCliClient.ServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/EditTodoItem", ReplyAction="http://tempuri.org/ITodoService/EditTodoItemResponse")]
        System.Threading.Tasks.Task EditTodoItemAsync(TodoCliClient.ServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/DeleteTodoItem", ReplyAction="http://tempuri.org/ITodoService/DeleteTodoItemResponse")]
        System.Threading.Tasks.Task DeleteTodoItemAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ITodoServiceChannel : TodoCliClient.ServiceReference.ITodoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TodoServiceClient : System.ServiceModel.ClientBase<TodoCliClient.ServiceReference.ITodoService>, TodoCliClient.ServiceReference.ITodoService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TodoServiceClient() : 
                base(TodoServiceClient.GetDefaultBinding(), TodoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITodoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TodoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TodoServiceClient.GetBindingForEndpoint(endpointConfiguration), TodoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TodoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TodoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TodoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TodoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TodoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TodoCliClient.ServiceReference.TodoItem[]> GetTodoItemsAsync()
        {
            return base.Channel.GetTodoItemsAsync();
        }
        
        public System.Threading.Tasks.Task CreateTodoItemAsync(TodoCliClient.ServiceReference.TodoItem item)
        {
            return base.Channel.CreateTodoItemAsync(item);
        }
        
        public System.Threading.Tasks.Task EditTodoItemAsync(TodoCliClient.ServiceReference.TodoItem item)
        {
            return base.Channel.EditTodoItemAsync(item);
        }
        
        public System.Threading.Tasks.Task DeleteTodoItemAsync(string id)
        {
            return base.Channel.DeleteTodoItemAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITodoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITodoService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:58332/TodoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TodoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITodoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TodoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITodoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITodoService,
        }
    }
}
